version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- cmd: dotnet restore src/Vlingo.Actors.sln
build:
  project: src/Vlingo.Actors.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- cmd: dotnet test src/Vlingo.Actors.Tests
deploy:
- provider: NuGet
  api_key:
    secure: gBHhsi+2P2E6AKjO3DziI2YKKeJ+SOqXbssbUNVzJEEiMXDSpHlnpbDfObTifbUd
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master